# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Redeploy Application
          command: ssh -o "StrictHostKeyChecking no" -v $DROPLET_USER@$DROPLET_IP "cd /var/www/sjsiceteam.com/services; git pull origin master; yarn install; yarn build; pm2 restart 1"
